embulk:
  build: ./embulk
  hostname: embulk
  volumes:
    - ./embulk/data:/data
    - ./embulk/config:/config
    - ./embulk/scripts:/scripts
    - ./embulk/logs:/logs
  external_links:
    - rdocumentationelasticsearch_es_1:es
  restart: always