es:  
  image: elasticsearch
  volumes:
    - ./config:/usr/share/elasticsearch/config
  ports:
    - "9200:9200"
    - "9300:9300"
  restart: always
kibana:
  image: kibana
  environment:
    - ELASTICSEARCH_URL=http://es:9200
  ports: 
   - "5601:5601"
  links: 
   - es