version: "3"
services:
  es:  
    build: ./config
    ports:
    - "9200:9200"
    - "9300:9300"
    networks:
      - es
  kibana:
    image: kibana:4.5
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    ports: 
    - "5601:5601"
    networks:
      - es
networks:
  es:
    driver: bridge