version: 2.1
orbs:
  queue: eddiewebb/queue@1.6.4
  datacamp-artifactory: datacamp/artifactory@1

workflows:
  main:
    jobs:
      - queue/block_workflow:
          name: queue
          context: org-global
          time: '10'

      - datacamp-artifactory/build_and_push_image_to_artifactory:
          name: docker-build
          context: org-global
          extra-docker-args: '--build-arg VERSION=$(git describe --tags)'
          dockerfile: logstash/Dockerfile
          docker-version: 20.10.2
          executor: datacamp-artifactory/buildkit
          path: logstash
          repo: rdoc-logstash
          requires:
            - queue

      - datacamp-artifactory/tag_repository:
          name: tag
          context: org-global
          requires:
            - docker-build
          filters:
            branches:
              only:
                - master
