version: 2.1
orbs:
  datacamp-ecr: datacamp/ecr@1.5.0
  datacamp-deploy: datacamp/deploy@2.0.0
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - datacamp-ecr/build_and_push_image_to_ecr:
          name: build
          context: org-global
          aws-access-key-id: $STAGING_AWS_ACCESS_KEY_ID
          aws-secret-access-key: $STAGING_AWS_SECRET_ACCESS_KEY
          account-url: $STAGING_ECR_URL
          region: us-east-1
          repo: rdoc-logstash
          path: logstash
          dockerfile: logstash/Dockerfile
      - datacamp-deploy/deploy: # Staging ECS
          name: deploy-staging
          context: org-global
          requires:
            - build
          aws-access-key-id: $STAGING_AWS_ACCESS_KEY_ID
          aws-secret-access-key: $STAGING_AWS_SECRET_ACCESS_KEY
          environment: staging
          extra-env: "SERVICE=rdoc-logstash DESIRED_COUNT=1 CLUSTER=datacamp-services ENVIRONMENT=staging"
          filters:
            branches:
              only:
                - master
      - datacamp-ecr/pull_push_to_account:
          context: org-global
          repo: rdoc-logstash
          requires:
            - deploy-staging
          filters:
            branches:
              only:
                - master
      - datacamp-deploy/deploy: # Production ECS
          name: deploy-production
          context: org-global
          requires:
            - datacamp-ecr/pull_push_to_account
          aws-access-key-id: $PROD_AWS_ACCESS_KEY_ID
          aws-secret-access-key: $PROD_AWS_SECRET_ACCESS_KEY
          environment: prod
          extra-env: "SERVICE=rdoc-logstash DESIRED_COUNT=1 CLUSTER=datacamp-services ENVIRONMENT=prod"
          filters:
            branches:
              only:
                - master
