in:
  type: mysql
  host: {{ .Env.DB_HOST }}
  user: {{ .Env.DB_USER }}
  password: "{{ .Env.DB_PASSWORD }}"
  database: {{ .Env.DB_NAME }}
  query: |
    select p.name as id, r.`name` = 'part_of_r' as part_of_r, s.downloads as last_month_downloads from Packages p 
      INNER JOIN (select SUM(s.`direct_downloads`) as downloads, s.package_name FROM DownloadStatistics s WHERE `date` >= current_date() - interval '1' month GROUP BY package_name) as s 
      ON s.package_name = p.name 
      INNER JOIN Repositories r on p.type_id = r.id;
out:
  type: elasticsearch
  index: rdoc_v4
  index_type: package
  id: "id"
  cluster_name: rdoc
  nodes:
  - host: es
