packages:
  build: "."
  hostname: embulk
  entrypoint: 
   - /entrypoint.sh
   - packages
  environment:
    - DB_HOST=rdocsv2.cwvhgphxbnoa.us-west-1.rds.amazonaws.com
    - DB_USER=aws
    - DB_PASSWORD=SQhBVFNvvMX4sEb5FKEYVjhG
    - DB_NAME=rdocs
  external_links:
    - rdocumentationelasticsearch_es_1:es
versions:
  build: "."
  hostname: embulk
  entrypoint: 
   - /entrypoint.sh
   - versions
  environment:
    - DB_HOST=rdocsv2.cwvhgphxbnoa.us-west-1.rds.amazonaws.com
    - DB_USER=aws
    - DB_PASSWORD=SQhBVFNvvMX4sEb5FKEYVjhG
    - DB_NAME=rdocs
  external_links:
    - rdocumentationelasticsearch_es_1:es
topics:
  build: "."
  hostname: embulk
  entrypoint: 
   - /entrypoint.sh
   - topics
  environment:
    - DB_HOST=rdocsv2.cwvhgphxbnoa.us-west-1.rds.amazonaws.com
    - DB_USER=aws
    - DB_PASSWORD=SQhBVFNvvMX4sEb5FKEYVjhG
    - DB_NAME=rdocs
  external_links:
    - rdocumentationelasticsearch_es_1:es
